# config.py — Central event configuration
# Required event inputs live in ../input.py. This file is for optional report
# polish, topic quality, forecast tuning, and derived paths.

import importlib.util
import os
from pathlib import Path


_INPUT_PATH = Path(__file__).resolve().parents[1] / "input.py"
_INPUT_SPEC = importlib.util.spec_from_file_location("forecast_input", _INPUT_PATH)
if _INPUT_SPEC is None or _INPUT_SPEC.loader is None:
    raise ImportError(f"Could not load required forecast inputs from {_INPUT_PATH}")
_INPUT = importlib.util.module_from_spec(_INPUT_SPEC)
_INPUT_SPEC.loader.exec_module(_INPUT)


def _required_input(name: str):
    try:
        return getattr(_INPUT, name)
    except AttributeError as exc:
        raise AttributeError(f"Missing required input.py value: {name}") from exc


EVENT_NAME = _required_input("EVENT_NAME")
EVENT_KEY = _required_input("EVENT_KEY")
ARTICLE_LANGUAGE = _required_input("ARTICLE_LANGUAGE")
EVENT_ANCHORS = _required_input("EVENT_ANCHORS")
EVENT_ENDS = _required_input("EVENT_ENDS")
FORECAST_YEAR = _required_input("FORECAST_YEAR")
BASE_YEAR = _required_input("BASE_YEAR")
COMPARE_YEAR = _required_input("COMPARE_YEAR")
FORECAST_WINDOW_START = _required_input("FORECAST_WINDOW_START")
FORECAST_WINDOW_END = _required_input("FORECAST_WINDOW_END")


# =============================================================================
# OPTIONAL TUNING / REPORT POLISH
# =============================================================================

# ── Forecast mix guardrails ────────────────────────────────────────────────────
# These floors prevent the forecast from becoming too spontaneous-heavy when a
# small input file over-represents breaking-news articles.
MIN_EVERGREEN_IMPRESSION_SHARE = 0.50
MIN_EVERGREEN_ARTICLE_SHARE = 0.50

# ── Single-year baseline forecast settings ─────────────────────────────────────
# Used by 3-forecast-baseline.py when BASE_YEAR data is missing. A multiplier of
# 1.0 means "repeat the COMPARE_YEAR curve"; 1.10 means "+10% vs compare year".
BASELINE_YEAR                  = COMPARE_YEAR
BASELINE_IMPRESSION_MULTIPLIER = 1.0
BASELINE_ARTICLE_MULTIPLIER    = 1.0

# ── Topic modelling stopwords ───────────────────────────────────────────────────
# Optional but strongly recommended: strip generic event words so topic clusters
# separate by what is being covered, not repeated event vocabulary.
DOMAIN_STOPWORDS = {
    "toronto", "international", "film", "festival", "tiff", "films", "movie",
    "movies", "cinema", "cinematic", "premiere", "premieres", "screening",
    "screenings", "review", "reviews", "red", "carpet", "interview", "interviews",
    "celebrity", "celebrities", "director", "directors", "actor", "actors",
    "actress", "actresses", "star", "stars", "cast", "trailer", "trailers",
    "documentary", "documentaries", "feature", "features", "short", "shorts",
    "show", "shows", "look", "looks", "style", "styles", "best", "top", "guide",
    "article", "articles", "photo", "photos", "video", "videos",
    "2025", "2026",
}

# ── Optional manual topic labels ────────────────────────────────────────────────
# Use this when the LLM labeler is unavailable or when a client-facing report needs
# curated naming. Leave this as {} for a new event unless you already know the
# deterministic topic ids generated by 2-find-topics.py.
MANUAL_TOPIC_LABELS = {
    "Evergreen_0": {
        "label": "Canadian Cult Comedy",
        "description": (
            "Matt Johnson and Nirvanna the Band coverage with a strong hometown "
            "comedy angle for Canadian film fans."
        ),
    },
    "Evergreen_1": {
        "label": "Music Documentary Nostalgia",
        "description": (
            "Lilith Fair and Degrassi documentary stories connecting TIFF to "
            "Canadian pop culture memory and music fandom."
        ),
    },
    "Evergreen_2": {
        "label": "Montreal Indie Music Fiction",
        "description": (
            "Mile End Kicks coverage built around Montreal music scenes, indie "
            "rock nostalgia, and Canadian auteur appeal."
        ),
    },
    "Evergreen_3": {
        "label": "Festival Reviews & Profiles",
        "description": (
            "Broad TIFF review and interview coverage spanning anticipated "
            "premieres, creator profiles, and music-linked films."
        ),
    },
    "Evergreen_4": {
        "label": "Tech Founder Biopics",
        "description": (
            "Swiped and Bumble-founder coverage focused on startup culture, tech "
            "mythology, and biographical drama."
        ),
    },
    "Evergreen_5": {
        "label": "Concert Week Crossovers",
        "description": (
            "Local concert guides and music-event coverage that overlaps with "
            "TIFF week audience planning."
        ),
    },
    "Evergreen_6": {
        "label": "Toronto On Screen",
        "description": (
            "Evergreen location-led coverage about Toronto as a film setting and "
            "cultural character."
        ),
    },
    "Evergreen_7": {
        "label": "John Candy Tribute Documentary",
        "description": (
            "John Candy documentary coverage driven by Canadian comedy legacy, "
            "nostalgia, and tribute storytelling."
        ),
    },
    "Evergreen_8": {
        "label": "Elvis Music Documentary",
        "description": (
            "High-interest Elvis and Baz Luhrmann music-documentary coverage with "
            "strong legacy artist appeal."
        ),
    },
    "Evergreen_9": {
        "label": "Hockey Drama Revival",
        "description": (
            "Youngblood coverage linking hockey nostalgia, 1980s genre memory, "
            "and Canadian sports-film interest."
        ),
    },
    "Spontaneous_0": {
        "label": "Entertainment News Spillover",
        "description": (
            "Fast-moving entertainment and music news adjacent to TIFF, including "
            "winners, retrospectives, and wider release chatter."
        ),
    },
    "Spontaneous_1": {
        "label": "International Family Dramas",
        "description": (
            "Rental Family and No Other Choice coverage centered on family, work, "
            "and international auteur storytelling."
        ),
    },
    "Spontaneous_2": {
        "label": "Degrassi Documentary Dispute",
        "description": (
            "Breaking coverage around the Degrassi documentary trailer, premiere, "
            "and Linda Schuyler lawsuit."
        ),
    },
    "Spontaneous_3": {
        "label": "Green Day Road Comedy",
        "description": (
            "Green Day New Year's Rev coverage connecting punk nostalgia, band "
            "fandom, and TIFF premiere news."
        ),
    },
    "Spontaneous_4": {
        "label": "Glenn-Copeland Kids Pilot",
        "description": (
            "Beverly Glenn-Copeland children's-show pilot coverage with a niche "
            "Canadian music and family-TV angle."
        ),
    },
    "Spontaneous_5": {
        "label": "James McAvoy Incident",
        "description": (
            "Breaking celebrity incident coverage from TIFF week, led by the "
            "reported James McAvoy bar assault."
        ),
    },
    "Spontaneous_6": {
        "label": "Celebrity Controversy Bits",
        "description": (
            "Short-lived celebrity and critic controversy stories with quick "
            "social-news attention."
        ),
    },
    "Spontaneous_7": {
        "label": "Ensemble Premiere Reviews",
        "description": (
            "Premiere and review coverage for ensemble titles such as Wake Up "
            "Dead Man, Dinner with Friends, and Friendship."
        ),
    },
    "Spontaneous_8": {
        "label": "Tribute Award Honorees",
        "description": (
            "TIFF Tribute Awards coverage highlighting Guillermo del Toro, Jodie "
            "Foster, HIKARI, and Lee Byung Hun."
        ),
    },
    "Spontaneous_9": {
        "label": "Political Documentary Protests",
        "description": (
            "Protest coverage around a politically sensitive documentary and "
            "activist response during TIFF."
        ),
    },
}

# ── Derived constants (no need to edit) ────────────────────────────────────────
EVENT_ANCHOR  = EVENT_ANCHORS[FORECAST_YEAR]   # Anchor date for the forecast year
EVENT_END     = EVENT_ENDS[FORECAST_YEAR]      # Final date of the forecast-year event
DEFAULT_REPORT_PATH = f"reports/{EVENT_KEY}_{FORECAST_YEAR}_forecast_report_v4.html"
DEFAULT_RECO_CSV_PATH = f"data/{EVENT_KEY}_{FORECAST_YEAR}_recommendations.csv"

REPORT_PATH   = os.getenv("REPORT_PATH", DEFAULT_REPORT_PATH)
RECO_CSV_PATH = os.getenv("RECO_CSV_PATH", DEFAULT_RECO_CSV_PATH)
