# config.py — Central event configuration
# Edit this file to switch between events (Black Friday, Easter, Christmas, etc.)

import os

import pandas as pd

# ── Event identity ──────────────────────────────────────────────────────────────
EVENT_NAME = "Toronto International Film Festival"  # Display name used in chart titles and reports
EVENT_KEY  = "toronto_international_film_festival" # Slug used in filenames (lowercase, underscores)
ARTICLE_LANGUAGE = "en"       # ISO 639-1 language code used by langdetect, e.g. "en" or "fr"

# ── Historical anchor dates + forecast target ───────────────────────────────────
# Add or remove years to match your available data.
EVENT_ANCHORS = {
    2025: pd.Timestamp("2025-09-04"),
    2026: pd.Timestamp("2026-09-10"),
}
EVENT_ENDS = {
    2025: pd.Timestamp("2025-09-14"),
    2026: pd.Timestamp("2026-09-20"),
}
FORECAST_YEAR = 2026   # Year to produce the forecast for
BASE_YEAR     = 2025   # Earliest year with data (used for YoY growth baseline)
COMPARE_YEAR  = 2025   # Most recent complete year (used as the projection base)

# ── Forecast activation window ─────────────────────────────────────────────────
# Recent pre-season data can inform topic discovery, but the deliverable forecast
# should stay inside the activation months for the event.
FORECAST_WINDOW_START = pd.Timestamp("2026-09-01")
FORECAST_WINDOW_END   = pd.Timestamp("2026-10-31")
MIN_EVERGREEN_IMPRESSION_SHARE = 0.50
MIN_EVERGREEN_ARTICLE_SHARE = 0.50

# ── Single-year baseline forecast settings ─────────────────────────────────────
# Used by 3-forecast-baseline.py when BASE_YEAR data is missing. A multiplier of
# 1.0 means "repeat the COMPARE_YEAR curve"; 1.10 means "+10% vs compare year".
BASELINE_YEAR                  = COMPARE_YEAR
BASELINE_IMPRESSION_MULTIPLIER = 1.0
BASELINE_ARTICLE_MULTIPLIER    = 1.0

# ── Topic modelling stopwords ───────────────────────────────────────────────────
# Words to strip from the bag-of-words so BERTopic clusters separate by
# *what's being covered* rather than the shared event vocabulary.
DOMAIN_STOPWORDS = {
    "toronto", "international", "film", "festival", "tiff", "films", "movie",
    "movies", "cinema", "cinematic", "premiere", "premieres", "screening",
    "screenings", "review", "reviews", "red", "carpet", "interview", "interviews",
    "celebrity", "celebrities", "director", "directors", "actor", "actors",
    "actress", "actresses", "star", "stars", "cast", "trailer", "trailers",
    "documentary", "documentaries", "feature", "features", "short", "shorts",
    "show", "shows", "look", "looks", "style", "styles", "best", "top", "guide",
    "article", "articles", "photo", "photos", "video", "videos",
    "2025", "2026",
}

# ── Optional manual topic labels ────────────────────────────────────────────────
# Use this when the LLM labeler is unavailable or when a client-facing report needs
# curated naming. Keys are the deterministic topic ids generated by 2-find-topics.py.
MANUAL_TOPIC_LABELS = {
    "Evergreen_0": {
        "label": "Canadian Cult Comedy",
        "description": (
            "Matt Johnson and Nirvanna the Band coverage with a strong hometown "
            "comedy angle for Canadian film fans."
        ),
    },
    "Evergreen_1": {
        "label": "Music Documentary Nostalgia",
        "description": (
            "Lilith Fair and Degrassi documentary stories connecting TIFF to "
            "Canadian pop culture memory and music fandom."
        ),
    },
    "Evergreen_2": {
        "label": "Montreal Indie Music Fiction",
        "description": (
            "Mile End Kicks coverage built around Montreal music scenes, indie "
            "rock nostalgia, and Canadian auteur appeal."
        ),
    },
    "Evergreen_3": {
        "label": "Festival Reviews & Profiles",
        "description": (
            "Broad TIFF review and interview coverage spanning anticipated "
            "premieres, creator profiles, and music-linked films."
        ),
    },
    "Evergreen_4": {
        "label": "Tech Founder Biopics",
        "description": (
            "Swiped and Bumble-founder coverage focused on startup culture, tech "
            "mythology, and biographical drama."
        ),
    },
    "Evergreen_5": {
        "label": "Concert Week Crossovers",
        "description": (
            "Local concert guides and music-event coverage that overlaps with "
            "TIFF week audience planning."
        ),
    },
    "Evergreen_6": {
        "label": "Toronto On Screen",
        "description": (
            "Evergreen location-led coverage about Toronto as a film setting and "
            "cultural character."
        ),
    },
    "Evergreen_7": {
        "label": "John Candy Tribute Documentary",
        "description": (
            "John Candy documentary coverage driven by Canadian comedy legacy, "
            "nostalgia, and tribute storytelling."
        ),
    },
    "Evergreen_8": {
        "label": "Elvis Music Documentary",
        "description": (
            "High-interest Elvis and Baz Luhrmann music-documentary coverage with "
            "strong legacy artist appeal."
        ),
    },
    "Evergreen_9": {
        "label": "Hockey Drama Revival",
        "description": (
            "Youngblood coverage linking hockey nostalgia, 1980s genre memory, "
            "and Canadian sports-film interest."
        ),
    },
    "Spontaneous_0": {
        "label": "Entertainment News Spillover",
        "description": (
            "Fast-moving entertainment and music news adjacent to TIFF, including "
            "winners, retrospectives, and wider release chatter."
        ),
    },
    "Spontaneous_1": {
        "label": "International Family Dramas",
        "description": (
            "Rental Family and No Other Choice coverage centered on family, work, "
            "and international auteur storytelling."
        ),
    },
    "Spontaneous_2": {
        "label": "Degrassi Documentary Dispute",
        "description": (
            "Breaking coverage around the Degrassi documentary trailer, premiere, "
            "and Linda Schuyler lawsuit."
        ),
    },
    "Spontaneous_3": {
        "label": "Green Day Road Comedy",
        "description": (
            "Green Day New Year's Rev coverage connecting punk nostalgia, band "
            "fandom, and TIFF premiere news."
        ),
    },
    "Spontaneous_4": {
        "label": "Glenn-Copeland Kids Pilot",
        "description": (
            "Beverly Glenn-Copeland children's-show pilot coverage with a niche "
            "Canadian music and family-TV angle."
        ),
    },
    "Spontaneous_5": {
        "label": "James McAvoy Incident",
        "description": (
            "Breaking celebrity incident coverage from TIFF week, led by the "
            "reported James McAvoy bar assault."
        ),
    },
    "Spontaneous_6": {
        "label": "Celebrity Controversy Bits",
        "description": (
            "Short-lived celebrity and critic controversy stories with quick "
            "social-news attention."
        ),
    },
    "Spontaneous_7": {
        "label": "Ensemble Premiere Reviews",
        "description": (
            "Premiere and review coverage for ensemble titles such as Wake Up "
            "Dead Man, Dinner with Friends, and Friendship."
        ),
    },
    "Spontaneous_8": {
        "label": "Tribute Award Honorees",
        "description": (
            "TIFF Tribute Awards coverage highlighting Guillermo del Toro, Jodie "
            "Foster, HIKARI, and Lee Byung Hun."
        ),
    },
    "Spontaneous_9": {
        "label": "Political Documentary Protests",
        "description": (
            "Protest coverage around a politically sensitive documentary and "
            "activist response during TIFF."
        ),
    },
}

# ── Derived constants (no need to edit) ────────────────────────────────────────
EVENT_ANCHOR  = EVENT_ANCHORS[FORECAST_YEAR]   # Anchor date for the forecast year
EVENT_END     = EVENT_ENDS[FORECAST_YEAR]      # Final date of the forecast-year event
DEFAULT_REPORT_PATH = f"reports/{EVENT_KEY}_{FORECAST_YEAR}_forecast_report_v4.html"
DEFAULT_RECO_CSV_PATH = f"data/{EVENT_KEY}_{FORECAST_YEAR}_recommendations.csv"

REPORT_PATH   = os.getenv("REPORT_PATH", DEFAULT_REPORT_PATH)
RECO_CSV_PATH = os.getenv("RECO_CSV_PATH", DEFAULT_RECO_CSV_PATH)
