# config.py — Central event configuration
# Required event inputs live in ../input.py. This file is for optional report
# polish, topic quality, forecast tuning, and derived paths.

import importlib.util
import os
import re
import unicodedata
from pathlib import Path


_INPUT_PATH = Path(__file__).resolve().parents[1] / "input.py"
_INPUT_SPEC = importlib.util.spec_from_file_location("forecast_input", _INPUT_PATH)
if _INPUT_SPEC is None or _INPUT_SPEC.loader is None:
    raise ImportError(f"Could not load required forecast inputs from {_INPUT_PATH}")
_INPUT = importlib.util.module_from_spec(_INPUT_SPEC)
_INPUT_SPEC.loader.exec_module(_INPUT)


def _required_input(name: str):
    try:
        return getattr(_INPUT, name)
    except AttributeError as exc:
        raise AttributeError(f"Missing required input.py value: {name}") from exc


def _slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-z0-9]+", "_", ascii_value.lower()).strip("_")
    return re.sub(r"_+", "_", slug)


EVENT_NAME = _required_input("EVENT_NAME")
EVENT_KEY = _slugify(EVENT_NAME)
ARTICLE_LANGUAGE = _required_input("ARTICLE_LANGUAGE")
EVENT_ANCHORS = _required_input("EVENT_ANCHORS")
EVENT_ENDS = _required_input("EVENT_ENDS")
FORECAST_YEAR = _required_input("FORECAST_YEAR")
BASE_YEAR = _required_input("BASE_YEAR")
COMPARE_YEAR = _required_input("COMPARE_YEAR")
FORECAST_WINDOW_START = _required_input("FORECAST_WINDOW_START")
FORECAST_WINDOW_END = _required_input("FORECAST_WINDOW_END")


# =============================================================================
# OPTIONAL TUNING / REPORT POLISH
# =============================================================================

# ── Forecast planning mix ──────────────────────────────────────────────────────
# Calibrate the business-facing impression mix toward an 80% evergreen target
# while retaining some influence from the observed data. Bounds prevent both an
# overly spontaneous forecast and a mechanically fixed 80/20 result.
EVERGREEN_PLANNING_TARGET = 0.80
EVERGREEN_OBSERVED_WEIGHT = 0.20
MIN_EVERGREEN_IMPRESSION_SHARE = 0.70
MAX_EVERGREEN_IMPRESSION_SHARE = 0.90

# Keep article classification untouched as the model's observed diagnostic.
MIN_EVERGREEN_ARTICLE_SHARE = 0.00

# ── Single-year baseline forecast settings ─────────────────────────────────────
# Used by 3-forecast-baseline.py when BASE_YEAR data is missing. A multiplier of
# 1.0 means "repeat the COMPARE_YEAR curve"; 1.10 means "+10% vs compare year".
BASELINE_YEAR                  = COMPARE_YEAR
BASELINE_IMPRESSION_MULTIPLIER = 1.0
BASELINE_ARTICLE_MULTIPLIER    = 1.0

# ── Topic modelling stopwords ───────────────────────────────────────────────────
# Optional but strongly recommended: strip generic event words so topic clusters
# separate by what is being covered, not repeated event vocabulary.
DOMAIN_STOPWORDS = {
    "toronto", "international", "film", "festival", "tiff", "films", "movie",
    "movies", "cinema", "cinematic", "premiere", "premieres", "screening",
    "screenings", "review", "reviews", "red", "carpet", "interview", "interviews",
    "celebrity", "celebrities", "director", "directors", "actor", "actors",
    "actress", "actresses", "star", "stars", "cast", "trailer", "trailers",
    "documentary", "documentaries", "feature", "features", "short", "shorts",
    "show", "shows", "look", "looks", "style", "styles", "best", "top", "guide",
    "article", "articles", "photo", "photos", "video", "videos",
    "2025", "2026",
}

# ── Optional manual topic labels ────────────────────────────────────────────────
# Use this when the LLM labeler is unavailable or when a client-facing report needs
# curated naming. Leave this as {} for a new event unless you already know the
# deterministic topic ids generated by 2-find-topics.py.
MANUAL_TOPIC_LABELS = {
    "Evergreen_0": {
        "label": "Amazon Shopping Hacks",
        "description": "Roundups of inexpensive Amazon products, clever home upgrades, gifts, and practical everyday finds. The coverage emphasizes surprising usefulness, strong reviews, and affordable solutions to common problems.",
    },
    "Evergreen_1": {
        "label": "Reality TV & Celebrity Culture",
        "description": "Profiles and explainers about reality-TV personalities, celebrity relationships, transformations, and family histories. The stories provide background on cast members, personal milestones, and recurring franchise narratives.",
    },
    "Evergreen_2": {
        "label": "Reference Lists & Archives",
        "description": "Reference-style lists, rankings, newspaper archives, recruiting pages, and historical records. These pages are designed for repeated lookup and remain useful long after their original publication date.",
    },
    "Evergreen_3": {
        "label": "Broad Culture & General Interest",
        "description": "A high-volume mix of entertainment, sports, technology, awards, current affairs, and general reference content. The cluster captures widely useful or frequently revisited stories that do not fit within one narrow editorial vertical.",
    },
    "Evergreen_4": {
        "label": "Red Carpet Style & Transformations",
        "description": "Celebrity transformations, red-carpet retrospectives, memorable outfits, and appearance-led profiles. The focus is on visual evolution, styling choices, body transformations, and standout public appearances.",
    },
    "Evergreen_5": {
        "label": "Outdoor Gear & Performance",
        "description": "Reviews and practical guides for cycling, boating, climbing, vehicles, and performance equipment. The articles compare specifications, explain product choices, and help enthusiasts improve how they travel or train.",
    },
    "Evergreen_6": {
        "label": "Golf Equipment Guides",
        "description": "Buying guides and advice for golf clubs, drivers, hybrids, footwear, and electric trolleys. The coverage matches equipment to skill level, swing speed, budget, and desired performance improvements.",
    },
    "Evergreen_7": {
        "label": "Sports Game Guides",
        "description": "Madden player guides, football recruiting references, and sports-game roster resources. These pages help readers compare players, abilities, historical classes, and in-game performance attributes.",
    },
    "Evergreen_8": {
        "label": "Character & Franchise Analysis",
        "description": "Character analysis and franchise discussion focused on motivations, rivalries, and controversial story decisions. The cluster is led by retrospective coverage of Hawk and other Cobra Kai characters.",
    },
    "Evergreen_9": {
        "label": "Gaming Wikis & Lore",
        "description": "Game-wiki entries, boss guides, character pages, item references, and franchise lore. The content supports players looking for locations, combat strategies, statistics, equipment details, and story background.",
    },
    "Evergreen_10": {
        "label": "Beauty & Shopping Guides",
        "description": "Beauty, hair, makeup, skincare, gift, and affordable-product guides. The stories combine practical recommendations with celebrity-inspired looks, mature-skin advice, and products that simplify everyday routines.",
    },
    "Evergreen_11": {
        "label": "Celebrity & Entertainment Profiles",
        "description": "Celebrity interviews, television explainers, lifestyle profiles, and entertainment retrospectives. The cluster explores careers, personal histories, cast changes, show mythology, and memorable moments from popular culture.",
    },
    "Evergreen_12": {
        "label": "Music & Artist Culture",
        "description": "Artist interviews, music history, song stories, guitar features, and musician profiles. The coverage combines technical insight with behind-the-scenes accounts of bands, recordings, performances, and influential careers.",
    },
    "Evergreen_13": {
        "label": "Classic Hollywood Profiles",
        "description": "Biographical and historical profiles of stars from Hollywood's studio era. The cluster is led by Jean Harlow coverage examining fame, image, relationships, and the mythology surrounding classic cinema.",
    },
    "Evergreen_14": {
        "label": "Health & Medical Guides",
        "description": "Accessible explainers about symptoms, blood pressure, heart health, pain treatment, and chronic conditions. The articles help readers understand warning signs, common measurements, treatment options, and everyday health management.",
    },
    "Evergreen_15": {
        "label": "Streaming, Film & TV Discovery",
        "description": "Streaming watchlists, film and television explainers, episode schedules, franchise guides, and viewing recommendations. The cluster helps audiences decide what to watch and understand release timing, continuity, endings, and adaptations.",
    },
    "Evergreen_16": {
        "label": "Red Carpet Fashion",
        "description": "Celebrity outfits, awards fashion, beauty trends, red-carpet looks, and styling analysis. The emphasis is on silhouettes, designers, glamour references, beauty details, and the visual impact of public appearances.",
    },
    "Evergreen_17": {
        "label": "Wellness & Lifestyle",
        "description": "Yoga, stretching, strength, posture, mobility, and healthy-living guidance. The articles offer expert-led routines for reducing pain, counteracting sedentary habits, and maintaining flexibility and functional movement.",
    },
    "Spontaneous_0": {
        "label": "Broad TV & Entertainment News",
        "description": "Fast-moving coverage spanning television, streaming, wrestling, music, casting, and release news. The cluster follows current announcements, episode developments, franchise updates, and widely discussed entertainment moments.",
    },
    "Spontaneous_1": {
        "label": "Breaking News & Legal Controversies",
        "description": "Rapid coverage of lawsuits, criminal cases, public disputes, political conflict, and corporate legal action. These stories develop quickly and are driven by new allegations, court filings, official statements, and public reaction.",
    },
    "Spontaneous_2": {
        "label": "90 Day Fiance Updates",
        "description": "Relationship, cast, pregnancy, employment, and spin-off updates from the 90 Day Fiance franchise. The coverage tracks how couples and individual cast members evolve during and after filming.",
    },
    "Spontaneous_3": {
        "label": "Sheer Red Carpet Fashion",
        "description": "Celebrity-fashion coverage focused on sheer dresses, naked gowns, provocative styling, and press-tour looks. The stories react to boundary-pushing outfits and compare how stars interpret the same visual trend.",
    },
    "Spontaneous_4": {
        "label": "Celebrity Relationships & Family",
        "description": "Current celebrity dating, marriage, breakup, family, parenting, and friendship news. The cluster follows relationship timelines, public appearances, separations, rumors, and changes within well-known families.",
    },
    "Spontaneous_5": {
        "label": "Festival Premieres & Oscar Buzz",
        "description": "Premiere reactions, standing ovations, early reviews, box-office updates, and awards-season discussion around current films. The coverage captures how audience response and critical momentum build immediately after screenings.",
    },
    "Spontaneous_6": {
        "label": "Celebrity Life & Reality TV",
        "description": "High-volume celebrity updates covering marriages, family life, careers, reality television, and personal milestones. The stories are driven by interviews, social posts, television appearances, and newly announced life events.",
    },
    "Spontaneous_7": {
        "label": "TV Cast & Celebrity Family Updates",
        "description": "Current television casting, trailers, celebrity children, separations, and music-competition news. The cluster links production updates with personal developments involving actors, musicians, and their families.",
    },
    "Spontaneous_8": {
        "label": "Celebrity Red Carpet & Dating News",
        "description": "Red-carpet appearances, dating reports, celebrity style, streaming premieres, and entertainment-event coverage. The focus is on who attended, what they wore, relationship signals, and notable moments from public appearances.",
    },
    "Spontaneous_9": {
        "label": "Royal Family Updates",
        "description": "Current coverage of Prince Harry, Meghan Markle, Prince William, royal relationships, and monarchy-linked television. The stories examine public appearances, family tensions, media projects, and changing royal responsibilities.",
    },
    "Spontaneous_10": {
        "label": "Amanda Knox & Smashing Machine",
        "description": "Current stories about Amanda Knox dramatizations and Dwayne Johnson's The Smashing Machine. The cluster combines true-crime adaptation explainers with performance coverage, premiere reactions, and transformation stories.",
    },
    "Spontaneous_11": {
        "label": "Football News & Fantasy",
        "description": "College football, NFL, fantasy lineup, player ranking, injury, and weekly game coverage. The articles respond to recent results and help readers evaluate teams, players, matchups, and roster decisions.",
    },
    "Spontaneous_12": {
        "label": "Mormon Wives & Reality TV",
        "description": "Updates about Mormon Wives, Taylor Frankie Paul, Jen Hatmaker, Dancing with the Stars, and related personalities. The cluster follows relationship revelations, cast reactions, franchise crossovers, and new reality-TV roles.",
    },
    "Spontaneous_13": {
        "label": "Celebrity Photo Galleries",
        "description": "Celebrity event and premiere photo galleries, outfit posts, family appearances, and red-carpet images. The coverage is visual and immediate, documenting arrivals, styling details, and notable public moments.",
    },
    "Spontaneous_14": {
        "label": "Trump & US Politics",
        "description": "Fast-moving US political coverage centered on Donald Trump, his administration, courts, foreign policy, and media response. The stories track official decisions, legal challenges, international meetings, and political criticism.",
    },
    "Spontaneous_15": {
        "label": "Saturday Night Live News",
        "description": "Saturday Night Live cast changes, hosts, musical guests, sketches, controversies, and season developments. The cluster follows announcements and reactions as each episode or personnel change enters the news cycle.",
    },
    "Spontaneous_16": {
        "label": "Taylor Swift & Celebrity News",
        "description": "Taylor Swift, the Kelce family, Kardashians and Jenners, music releases, and adjacent celebrity stories. The coverage blends career announcements, relationships, family moments, fashion, and high-profile public appearances.",
    },
    "Spontaneous_17": {
        "label": "Awards Fashion & TV Reunions",
        "description": "Awards red-carpet fashion, celebrity style retrospectives, and television reunion moments such as Gilmore Girls. The cluster connects visual event coverage with nostalgia for familiar casts, characters, and screen partnerships.",
    },
}

# ── Derived constants (no need to edit) ────────────────────────────────────────
EVENT_ANCHOR  = EVENT_ANCHORS[FORECAST_YEAR]   # Anchor date for the forecast year
EVENT_END     = EVENT_ENDS[FORECAST_YEAR]      # Final date of the forecast-year event
DEFAULT_REPORT_PATH = f"reports/{EVENT_KEY}_{FORECAST_YEAR}_forecast_report_v4.html"
DEFAULT_RECO_CSV_PATH = f"data/{EVENT_KEY}_{FORECAST_YEAR}_recommendations.csv"

REPORT_PATH   = os.getenv("REPORT_PATH", DEFAULT_REPORT_PATH)
RECO_CSV_PATH = os.getenv("RECO_CSV_PATH", DEFAULT_RECO_CSV_PATH)
